
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-SellingNegativeCows","number":33,"title":"Angelina selling negative cows","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/33"},{"author":{"id":"U_kgDOBX2mjA","is_bot":false,"login":"ahjsuy","name":""},"headRefName":"Angelina-BuyNegativeCows","number":31,"title":"AS - disallowed buying negative cows + tests","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/31"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-IssueF1-2","number":30,"title":"Rohan Issue F1: Frontend for AnnouncementForm and Table along with Stories and Tests","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/30"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-IssueB2","number":28,"title":"Rohan Issue B2: CRUD Operations for Announcement Endpoints","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/28"}]
