
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"KylebKumar-edit-README","number":41,"title":"Add Deployments to README.md","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/41"},{"author":{"id":"MDQ6VXNlcjc0ODAwNTg1","is_bot":false,"login":"AlexLim-Pro","name":"Alex Lim"},"headRefName":"OurtablePagination","number":40,"title":"updated table to use pagination","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/40"}]
