
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-happy-cows-w24-4pm-2
owner: ucsb-cs156-w24
repo_name: proj-happy-cows-w24-4pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMjg5NDM1","is_bot":false,"login":"BK1031","name":"Bharat Kathi"},"headRefName":"Bharat-LeaderboardBackButton","number":39,"title":"Bharat UX Improvements to Leaderboard page","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/39"},{"author":{"id":"MDQ6VXNlcjMzMjg5NDM1","is_bot":false,"login":"BK1031","name":"Bharat Kathi"},"headRefName":"Bharat-FasterImageLoading","number":38,"title":"Bharat faster image loading","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/38"},{"author":{"id":"MDQ6VXNlcjYxNjM1Njk1","is_bot":false,"login":"rkirsur","name":"Ritu Kirsur"},"headRefName":"Ritu-FutureDateBug","number":37,"title":"Ritu Commons with future dates not able to be joined bug","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/37"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"add-showChat-checkbox-to-commons-form","number":36,"title":"Add show chat checkbox to commons form","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/36"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"add-showChat-to-commonsOverview","number":35,"title":"Add show chat to commons table","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/35"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"enable-admins-to-set-showChat","number":34,"title":"Enabled admins to set showChat in API","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/34"},{"author":{"id":"U_kgDOBXgO1Q","is_bot":false,"login":"rohankumar2025","name":""},"headRefName":"Rohan-IssueF1-2","number":30,"title":"Rohan Issue F1 + B2: Frontend for AnnouncementForm/Table and Backend CRUD Operations for Announcement Endpoints","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/30"},{"author":{"id":"MDQ6VXNlcjYxOTUwOTA5","is_bot":false,"login":"KylebKumar","name":"Kyle Kumar"},"headRefName":"small-bug-fix","number":19,"title":"Fixed usage of class -> className","url":"https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-2/pull/19"}]
